name: build pdf
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container: 
      image: docker.pkg.github.com/ikstream/tex-builder/tex-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make pdf
